<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="./styles/css/yes_style.css">
</head>
<body>
    <div class="container">
        <div class="second_text">
            <h1 class = "header_text">Урааа, спасибо! </h1>
        </div>
        <div class="gif_container">
            <img src="./styles/images/cute-cat.gif" alt="Cute animated illustration">
        </div>
<!--        <p class = "text">Тогда увидимся!!!!</p>-->
    </div>
</body>
</html>
